version: '3.8'
services: 
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    command: 'python manage.py runserver 0.0.0.0:8000'
    networks:
      blog-network:
        ipv4_address: 172.26.0.2
      default:
    extra_hosts:
      - "adminhost:172.26.0.2"
    ports: 
      - 8000:8000
    expose:
      - 8000
    volumes:
      - .:/app
    depends_on:
      - db

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python -u consumer.py'
    networks:
      blog-network:
        ipv4_address: 172.26.0.7
      default:
    depends_on:
      - db
      - backend

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports: 
      - 3306:3306

networks:
  blog-network:
    external: true
